# Paste the code generated by Azure AI Foundry for Marcus (Chat) here.
# This file is intended to store the raw reference code from Foundry.
# The actual integration should happen in `clients/marcus.py` using the shared ChatClient.
