import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { listStories } from '../../services/api';
import './StoriesPage.css';

interface StoryItem {
    story_id: string;
    topic: string;
    created_at: string;
    story_path: string;
}

export function StoriesPage() {
    const navigate = useNavigate();
    const [stories, setStories] = useState<StoryItem[]>([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        const fetchStories = async () => {
            try {
                const data = await listStories();
                setStories(data);
            } catch (err: any) {
                setError(err.message || 'Failed to load stories');
            } finally {
                setLoading(false);
            }
        };

        fetchStories();
    }, []);

    if (loading) return <div className="stories-loading">Loading artifacts...</div>;
    if (error) return <div className="stories-error">Error: {error}</div>;

    return (
        <div className="stories-page">
            <header className="stories-header">
                <h1>Sage's Artifacts</h1>
                <p className="subtitle">Collaborative stories and architectural diagrams generated by Sage Meridian.</p>
            </header>

            <div className="stories-grid">
                {stories.map(story => (
                    <div
                        key={story.story_id}
                        className="story-card"
                        onClick={() => navigate(`/stories/${story.story_id}`)}
                    >
                        <div className="story-icon">📜</div>
                        <div className="story-content">
                            <h3>{story.topic}</h3>
                            <span className="story-date">
                                {new Date(story.created_at).toLocaleDateString()}
                            </span>
                        </div>
                        <div className="story-arrow">→</div>
                    </div>
                ))}

                {stories.length === 0 && (
                    <div className="no-stories">
                        No artifacts found. Ask Sage to "create a story" to generate some!
                    </div>
                )}
            </div>
        </div>
    );
}
