#!/usr/bin/env python3
"""
Create GitHub Projects Story via Azure Engram API

This script calls the Azure-deployed Engram API to create a story
about GitHub Projects integration via Sage's delegation.
"""

import os
import sys
import json
import requests
from pathlib import Path

# Get API endpoint from environment or use default
API_URL = os.getenv("ENGRAM_API_URL", "https://engram-api.azurecontainerapps.io")
API_KEY = os.getenv("ENGRAM_API_KEY", "")

def create_story_via_api():
    """Create story via Azure Engram API"""
    
    print("📖 Creating GitHub Projects Story via Azure Engram API")
    print(f"🔗 API Endpoint: {API_URL}")
    print()
    
    # Story creation request
    topic = "GitHub Projects Integration for Engram Context Engine"
    context = """The Engram Context Engine has integrated GitHub Projects to enable comprehensive tracking 
of the Production-Grade Agentic System implementation across all seven layers. This integration 
allows Elena (Business Analyst) and Marcus (Project Manager) agents to actively manage tasks, 
track progress, and maintain visibility. The story should cover:

1. How GitHub Projects applies to each of the seven layers of agentic AI systems
2. The progress tracking mechanism and task lifecycle
3. Agent capabilities and workflows
4. System awareness of progress
5. Benefits for agents, system, and users

The story should be engaging, technical but accessible, and highlight the recursive self-awareness 
of the agents tracking their own work."""
    
    payload = {
        "topic": topic,
        "context": context,
        "include_diagram": True,
        "diagram_type": "architecture"
    }
    
    print("📝 Request payload:")
    print(json.dumps(payload, indent=2))
    print()
    
    # Prepare headers
    headers = {
        "Content-Type": "application/json"
    }
    
    if API_KEY:
        headers["X-API-Key"] = API_KEY
        print("🔑 Using API key authentication")
    else:
        print("🔑 Using Azure authentication (Managed Identity)")
        # Try to get Azure access token
        try:
            import subprocess
            result = subprocess.run(
                ["az", "account", "get-access-token", "--resource", "https://management.azure.com", "--query", "accessToken", "-o", "tsv"],
                capture_output=True,
                text=True,
                timeout=5
            )
            if result.returncode == 0 and result.stdout.strip():
                headers["Authorization"] = f"Bearer {result.stdout.strip()}"
                print("   ✅ Azure token obtained")
            else:
                print("   ⚠️  Could not get Azure token, proceeding without auth")
        except Exception as e:
            print(f"   ⚠️  Could not get Azure token: {e}")
    
    print()
    print(f"🚀 Calling API: POST {API_URL}/api/v1/story/create")
    print()
    
    try:
        response = requests.post(
            f"{API_URL}/api/v1/story/create",
            headers=headers,
            json=payload,
            timeout=300  # 5 minutes for story generation
        )
        
        print(f"📊 Response Status: {response.status_code}")
        print()
        
        if response.status_code in [200, 201]:
            data = response.json()
            
            print("✅ Story created successfully!")
            print()
            print(json.dumps(data, indent=2))
            print()
            
            story_id = data.get("story_id")
            if story_id:
                print("📝 Story Details:")
                print(f"   Story ID: {story_id}")
                print(f"   Story Path: {data.get('story_path', 'N/A')}")
                print(f"   Diagram Path: {data.get('diagram_path', 'N/A')}")
                print(f"   Image Path: {data.get('image_path', 'N/A')}")
                print()
                print(f"🔗 View story at: {API_URL}/api/v1/story/{story_id}")
                print()
                
                story_content = data.get("story_content", "")
                if story_content:
                    print("📖 Story Preview:")
                    print(story_content[:500])
                    print("...")
            
            print()
            print("🎉 Story creation complete!")
            print()
            print("The story and visual have been:")
            print("  ✅ Generated by Sage via Temporal workflow")
            print("  ✅ Saved to docs folder (OneDrive sync)")
            print("  ✅ Automatically ingested into Zep memory")
            print()
            print("Next steps:")
            print(f"  1. Check docs/stories/ folder for generated files")
            print("  2. Verify story in Zep memory")
            print(f"  3. View story via API: {API_URL}/api/v1/story/{story_id}")
            
            return story_id
        else:
            print("❌ Failed to create story")
            print()
            print("Response body:")
            try:
                error_data = response.json()
                print(json.dumps(error_data, indent=2))
            except:
                print(response.text)
            print()
            print("Troubleshooting:")
            print(f"1. Check API endpoint is correct: {API_URL}")
            print("2. Verify API key is set (if required): export ENGRAM_API_KEY=your-key")
            print("3. Check Azure authentication (if using Managed Identity)")
            print("4. Verify backend service is running in Azure")
            return None
            
    except requests.exceptions.Timeout:
        print("❌ Request timed out (story generation may take several minutes)")
        print("   The workflow may still be running in Azure")
        print("   Check Temporal UI or workflow status endpoint")
        return None
    except requests.exceptions.RequestException as e:
        print(f"❌ Request failed: {e}")
        print()
        print("Troubleshooting:")
        print(f"1. Check API endpoint is accessible: {API_URL}")
        print("2. Verify network connectivity")
        print("3. Check if backend service is running")
        return None

if __name__ == "__main__":
    story_id = create_story_via_api()
    if story_id:
        print(f"\n✅ Success! Story ID: {story_id}")
        sys.exit(0)
    else:
        print("\n❌ Story creation failed")
        sys.exit(1)

