#!/bin/bash
# Create GitHub Projects Story via Azure Engram API

set -e

echo "📖 Creating GitHub Projects Story via Azure Engram API"
echo ""

# Get API endpoint from environment or use default
API_URL="${ENGRAM_API_URL:-https://engram-api.azurecontainerapps.io}"
API_KEY="${ENGRAM_API_KEY:-}"

if [ -z "$API_KEY" ]; then
    echo "⚠️  ENGRAM_API_KEY not set"
    echo "   Set it via: export ENGRAM_API_KEY=your-api-key"
    echo "   Or it will use Azure authentication if available"
fi

echo "🔗 API Endpoint: $API_URL"
echo ""

# Story creation request
TOPIC="GitHub Projects Integration for Engram Context Engine"
CONTEXT="The Engram Context Engine has integrated GitHub Projects to enable comprehensive tracking of the Production-Grade Agentic System implementation across all seven layers. This integration allows Elena (Business Analyst) and Marcus (Project Manager) agents to actively manage tasks, track progress, and maintain visibility. The story should cover: 1. How GitHub Projects applies to each of the seven layers of agentic AI systems 2. The progress tracking mechanism and task lifecycle 3. Agent capabilities and workflows 4. System awareness of progress 5. Benefits for agents, system, and users. The story should be engaging, technical but accessible, and highlight the recursive self-awareness of the agents tracking their own work."

# Prepare JSON payload using jq for proper escaping
JSON_PAYLOAD=$(jq -n \
  --arg topic "$TOPIC" \
  --arg context "$CONTEXT" \
  '{
    "topic": $topic,
    "context": $context,
    "include_diagram": true,
    "diagram_type": "architecture"
  }')

echo "📝 Request payload:"
echo "$JSON_PAYLOAD" | jq '.'
echo ""

# Make API request
echo "🚀 Calling API endpoint: POST $API_URL/api/v1/story/create"
echo ""

if [ -z "$API_KEY" ]; then
    # Use Azure authentication (Managed Identity or DefaultAzureCredential)
    RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer $(az account get-access-token --resource https://management.azure.com --query accessToken -o tsv 2>/dev/null || echo '')" \
        -d "$JSON_PAYLOAD" \
        "$API_URL/api/v1/story/create")
else
    # Use API key
    RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
        -H "Content-Type: application/json" \
        -H "X-API-Key: $API_KEY" \
        -d "$JSON_PAYLOAD" \
        "$API_URL/api/v1/story/create")
fi

# Extract HTTP status code (last line)
HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
BODY=$(echo "$RESPONSE" | sed '$d')

echo "📊 Response Status: $HTTP_CODE"
echo ""

if [ "$HTTP_CODE" -eq 200 ] || [ "$HTTP_CODE" -eq 201 ]; then
    echo "✅ Story created successfully!"
    echo ""
    echo "$BODY" | jq '.'
    echo ""
    
    STORY_ID=$(echo "$BODY" | jq -r '.story_id // empty')
    if [ -n "$STORY_ID" ]; then
        echo "📝 Story Details:"
        echo "   Story ID: $STORY_ID"
        echo "   Story Path: $(echo "$BODY" | jq -r '.story_path // "N/A"')"
        echo "   Diagram Path: $(echo "$BODY" | jq -r '.diagram_path // "N/A"')"
        echo "   Image Path: $(echo "$BODY" | jq -r '.image_path // "N/A"')"
        echo ""
        echo "🔗 View story at: $API_URL/api/v1/story/$STORY_ID"
        echo ""
        echo "📖 Story Preview:"
        echo "$BODY" | jq -r '.story_content // ""' | head -20
        echo "..."
    fi
else
    echo "❌ Failed to create story"
    echo ""
    echo "Response body:"
    echo "$BODY" | jq '.' 2>/dev/null || echo "$BODY"
    echo ""
    echo "Troubleshooting:"
    echo "1. Check API endpoint is correct: $API_URL"
    echo "2. Verify API key is set (if required)"
    echo "3. Check Azure authentication (if using Managed Identity)"
    echo "4. Verify backend service is running in Azure"
    exit 1
fi

echo ""
echo "🎉 Story creation complete!"
echo ""
echo "The story and visual have been:"
echo "  ✅ Generated by Sage via Temporal workflow"
echo "  ✅ Saved to docs folder (OneDrive sync)"
echo "  ✅ Automatically ingested into Zep memory"
echo ""
echo "Next steps:"
echo "  1. Check docs/stories/ folder for generated files"
echo "  2. Verify story in Zep memory"
echo "  3. View story via API: $API_URL/api/v1/story/$STORY_ID"

