#!/usr/bin/env python3
"""
Create Feature Release Episode (API Version)

This script generates a new "Feature Release" episode in Zep memory via the Engram API.
It uses the "Sage Meridian" persona (Creative Director) to make the update engaging.

Usage:
  python3 scripts/create_feature_episode.py --title "Mobile Visuals" --summary "Enhanced mobile experience" --changes "Clickable images,Better typography"

Prerequisites:
  - 'az login' must be performed
  - 'httpx' library
"""
import argparse
import sys
import os
import json
import subprocess
import httpx
from datetime import datetime

API_URL = os.environ.get("ENGRAM_API_URL", "https://api.engram.work")

def get_auth_token():
    """Get Azure AD token via Azure CLI (or None if using API Key)"""
    if os.environ.get("ENGRAM_API_KEY"):
        return None  # Will use API Key instead
        
    token = os.environ.get("ENGRAM_API_TOKEN")
    if token:
        return token
    
    print("🔑 Getting Azure Access Token...")
    try:
        result = subprocess.run(
            ["az", "account", "get-access-token", "--resource", "api://engram", "--query", "accessToken", "-o", "tsv"],
            capture_output=True, text=True, check=True
        )
        return result.stdout.strip()
    except subprocess.CalledProcessError as e:
        print(f"❌ Failed to get token: {e}")
        print("Please run 'az login' or set ENGRAM_API_KEY.")
        sys.exit(1)
    except FileNotFoundError:
        print("❌ 'az' CLI not found. Please install Azure CLI or set ENGRAM_API_KEY.")
        sys.exit(1)

def main():
    parser = argparse.ArgumentParser(description="Create a Feature Release Episode")
    parser.add_argument("--title", required=True, help="Feature title (e.g., 'Mobile UX Upgrade')")
    parser.add_argument("--summary", required=True, help="Brief summary of the feature")
    parser.add_argument("--changes", required=True, help="Comma-separated list of changes")
    
    args = parser.parse_args()
    
    # Generate Slugs & ID
    slug = args.title.lower().replace(" ", "-")
    date_str = datetime.now().strftime("%Y%m%d")
    session_id = f"release-{date_str}-{slug}"
    
    print(f"🚀 Creating Feature Episode: {session_id}")

    # Sage's Announcement Message
    changes_list = args.changes.split(",")
    formatted_changes = "\n".join([f"- {c.strip()}" for c in changes_list])
    
    content = f"""# 📢 Feature Update: {args.title}

{args.summary}

### ✨ What's New
{formatted_changes}

---
*Generated by Engineering Context Awareness System*
"""

    # Structured Metadata
    payload = {
        "text": content,
        "session_id": session_id,
        "speaker": "assistant",
        "agent_id": "sage",
        "channel": "release_notes",
        "metadata": {
             "title": f"Feature: {args.title}",
             "summary": args.summary,
             "type": "feature_release",
             "tags": ["changelog", "feature", "release"],
             "display_name": "Sage Meridian",
             "email": "sage@engram.work"
        }
    }
    
    # Auth Strategy
    api_key = os.environ.get("ENGRAM_API_KEY")
    headers = {"Content-Type": "application/json"}
    
    if api_key:
        print("🔑 Using API Key authentication")
        headers["X-API-Key"] = api_key
    else:
        token = get_auth_token()
        headers["Authorization"] = f"Bearer {token}"
    
    try:
        print(f"📡 Sending to API: {API_URL}/api/v1/memory/enrich")
        # Ensure timeout is sufficient
        response = httpx.post(f"{API_URL}/api/v1/memory/enrich", json=payload, headers=headers, timeout=15.0)
        
        if response.status_code == 200:
            data = response.json()
            print("✅ Feature Episode Created Successfully!")
            print(f"   Session ID: {data.get('session_id')}")
        else:
            print(f"⚠️ API Error ({response.status_code}): {response.text}")
            sys.exit(1)
            
    except Exception as e:
        print(f"❌ Connection Failed: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
